services:
  frontend:
    build:
      context: ./src/frontend
    ports:
      - "3000:80"
    environment:
      - TEXT_CONTENT=Witam! This is a custom message from docker-compose!
      - BACKEND_URL=http://localhost:8080

  backend:
    build:
      context: ./src/backend
    ports:
      - "8080:8080"
    environment:
      - TEXT_CONTENT=Witam! This is a custom message from docker-compose!
      - FRONTEND_URL=http://localhost:3000
