name: "Build and Publish Docker Image"

on:
  workflow_dispatch:
    inputs:
      acr_login_server:
        description: "ACR login server"
        required: true
        type: string
  workflow_call:
    inputs:
      acr_login_server:
        description: "ACR login server"
        required: true
        type: string
    outputs:
      image_tag:
        description: "Docker image tag"
        value: ${{ jobs.build.outputs.image_tag }}

env:
  AZ_CREDENTIALS: >
    {
      "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
      "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
      "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
      "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
    }

jobs:
  build:
    name: "Build and publish Docker image"
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.image_details.outputs.image_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ env.AZ_CREDENTIALS }}

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.acr_login_server }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build and push container image to ACR
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ inputs.acr_login_server }}/pytest:${{ github.sha }}
          build-args: |

          context: ./src/backend

      - name: Set image tag output
        id: image_details
        run: |
          echo "image_tag=${{ inputs.acr_login_server }}/pytest:${{ github.sha }}" >> $GITHUB_OUTPUT
