name: "Deploy to Azure"

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag"
        required: true
        type: string
      resource_group_name:
        description: "Resource group name"
        required: true
        type: string
      container_app_name:
        description: "Container app name"
        required: true
        type: string
  workflow_call:
    inputs:
      image_tag:
        description: "Docker image tag"
        required: true
        type: string
      resource_group_name:
        description: "Resource group name"
        required: true
        type: string
      container_app_name:
        description: "Container app name"
        required: true
        type: string

env:
  AZ_CREDENTIALS: >
    {
      "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
      "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
      "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
      "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
    }

jobs:
  deploy:
    name: "Deploy to Azure"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ env.AZ_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ inputs.image_tag }}
          resourceGroup: ${{ inputs.resource_group_name }}
          containerAppName: ${{ inputs.container_app_name }}
          targetPort: ${{ vars.BACKEND_PORT }}

      - name: Get deployment URLs
        run: |
          echo "Container App deployed successfully!"
          echo "Image: ${{ inputs.image_tag }}"
          echo "Resource Group: ${{ inputs.resource_group_name }}"
          echo "Container App: ${{ inputs.container_app_name }}"
