name: "Build and Publish Docker Image"

on:
  workflow_dispatch:
    inputs:
      acr_login_server:
        description: "ACR login server"
        required: true
        type: string
  workflow_call:
    inputs:
      acr_login_server:
        description: "ACR login server"
        required: true
        type: string
    outputs:
      frontend_image_tag:
        description: "Docker frontend image tag"
        value: ${{ jobs.build.outputs.frontend_image_tag }}

      backend_image_tag:
        description: "Docker backend image tag"
        value: ${{ jobs.build.outputs.backend_image_tag }}

env:
  AZ_CREDENTIALS: >
    {
      "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
      "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
      "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
      "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
    }

jobs:
  build:
    name: "Build and publish Docker image"
    environment: "production"
    runs-on: ubuntu-latest

    outputs:
      frontend_image_tag: ${{ steps.image_details.outputs.frontend_image_tag }}
      backend_image_tag: ${{ steps.image_details.outputs.backend_image_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ env.AZ_CREDENTIALS }}

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.acr_login_server }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build and push frontend container image to ACR
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ inputs.acr_login_server }}/pytest_frontend:${{ github.sha }}
          build-args: |

          context: ./src/frontend

      - name: Build and push backend container image to ACR
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ inputs.acr_login_server }}/pytest_backend:${{ github.sha }}
          build-args: |

          context: ./src/backend

      - name: Set image tag output
        id: image_details
        run: |
          echo "frontend_image_tag=${{ inputs.acr_login_server }}/pytest_frontend:${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "backend_image_tag=${{ inputs.acr_login_server }}/pytest_backend:${{ github.sha }}" >> $GITHUB_OUTPUT
