name: "Main Pipeline"

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**/*.md"

jobs:
  terraform:
    name: "Provision infrastructure"
    uses: ./.github/workflows/job_terraform.yml
    secrets: inherit

  build:
    name: "Build and publish Docker image"
    needs: terraform
    uses: ./.github/workflows/job_build.yml
    with:
      acr_login_server: ${{ needs.terraform.outputs.acr_login_server }}
    secrets: inherit

  deploy:
    name: "Deploy to Azure"
    needs: [terraform, build]
    uses: ./.github/workflows/job_deploy.yml
    with:
      image_tag: ${{ needs.build.outputs.image_tag }}
      resource_group_name: ${{ needs.terraform.outputs.resource_group_name }}
      container_app_name: ${{ needs.terraform.outputs.container_app_name }}
    secrets: inherit
