name: "Deploy pipeline"

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**/*.md"
      - "docker-compose.yml"

jobs:
  build:
    uses: ./.github/workflows/job_build.yml
    secrets: inherit

  terraform:
    uses: ./.github/workflows/job_terraform.yml
    needs: build
    with:
      frontend_image_tag: ${{ needs.build.outputs.frontend_image_tag }}
      backend_image_tag: ${{ needs.build.outputs.backend_image_tag }}
    secrets: inherit
